academia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='user_login'), 
    path('logout/', views.user_logout, name='user_logout'),
    path('', views.welcome, name='welcome'),
    path('lista-cursos/', views.lista_cursos, name='lista_cursos'),
    path('inscribirse/<int:curso_id>/', views.inscribirse_curso, name='inscribirse_curso'),
    path('detalle_curso/<int:curso_id>/', views.detalle_curso, name='detalle_curso'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('curso/<int:curso_id>/usuarios/', views.usuarios_inscritos_curso, name='usuarios_inscritos_curso'),
    path('profe/', views.lista_profe, name='lista_profe'),
    path('comentarios_alumno/', views.comentarios_alumno, name='comentarios_alumno'),
    path('editar_comentario/<int:comentario_id>/', views.editar_comentario, name='editar_comentario'),
    path('eliminar_comentario/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),
    path('nueva_respuesta/<int:comentario_id>/', views.nueva_respuesta, name='nueva_respuesta'),
    path('notificaciones/', views.mostrar_notificaciones, name='notificaciones'),
    path('editar-perfil/', views.editar_perfil_usuario, name='editar_perfil'),
    path('cursos-inscritos/', views.mostrar_cursos_inscritos, name='cursos_inscritos'),
    path('temario/<int:curso_id>/', views.mostrar_temario, name='mostrar_temario'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Cursos(models.Model):
    nombre = models.CharField(max_length=255)
    tipo = models.CharField(max_length=100)
    decribcion = models.CharField(max_length=255)
    años = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nombre
    
class OtraClase(models.Model):
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    foto_de_perfil = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    descripcion = models.TextField(blank=True)
    original = models.ForeignKey(User, on_delete=models.CASCADE)
    

class InscripcionCurso(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    curso = models.ForeignKey(Cursos, on_delete=models.CASCADE)
    fecha_inscripcion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Inscripción de {self.usuario.username} en {self.curso.nombre}"
    
class Profesor(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    imagen = models.ImageField(upload_to='profesor_images/', null=True, blank=True)
    cursos = models.ForeignKey(Cursos, on_delete=models.CASCADE)

    def __str__(self):
        return {self.nombre}


class Comentario(models.Model):
    alumno = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comentarios_likes', blank=True)

    def __str__(self):
        return f"Comentario de {self.alumno.username}"

    def toggle_like(self, user):
        if user in self.likes.all():
            self.likes.remove(user)
        else:
            self.likes.add(user)

    def can_edit(self, user):
        return user == self.alumno

    def delete_comment(self):
        self.likes.clear()  # Elimina todas las relaciones ManyToMany con usuarios
        self.delete()

class Respuesta(models.Model):
    comentario_padre = models.ForeignKey(Comentario, on_delete=models.CASCADE, related_name='respuestas')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Respuesta de {self.autor.username} al comentario {self.comentario_padre.id}"
    
    
class Notificacion(models.Model):
    destinatario = models.ForeignKey(User, on_delete=models.CASCADE)
    remitente = models.ForeignKey(User, related_name='notificaciones_enviadas', on_delete=models.CASCADE)
    tipo = models.CharField(max_length=20)  # Tipo de notificación: "like" o "respuesta"
    comentario = models.ForeignKey(Comentario, on_delete=models.CASCADE)
    vista = models.BooleanField(default=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    
    @staticmethod
    def create_like_notification(comentario, remitente, destinatario):
        # Crear notificación de like
        Notificacion.objects.create(destinatario=destinatario, remitente=remitente, tipo="like", comentario=comentario)

    @staticmethod
    def create_response_notification(comentario, remitente, destinatario):
        # Crear notificación de respuesta
        Notificacion.objects.create(destinatario=destinatario, remitente=remitente, tipo="respuesta", comentario=comentario)
    

class Temario(models.Model):
    curso = models.ForeignKey(Cursos, on_delete=models.CASCADE, related_name='temarios')
    titulo = models.CharField(max_length=255)
    descripcion = models.TextField()
    
    def __str__(self):
        return f"{self.titulo} - {self.curso.nombre}"

myapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import OtraClase
from django import forms
from .models import Cursos

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")
        

from .models import Comentario

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        
        
class OtraClaseForm(forms.ModelForm):
    class Meta:
        model = OtraClase
        fields = [ 'foto_de_perfil', 'descripcion']

    def __init__(self, *args, **kwargs):
        super(OtraClaseForm, self).__init__(*args, **kwargs)
        self.fields['foto_de_perfil'].required = False  # Hacer que la foto de perfil no sea obligatoria en la edición  # Lista de campos que deseas editar en el formulario
        
        


class InscripcionForm(forms.Form):
    curso_id = forms.ModelChoiceField(queryset=Cursos.objects.all(), widget=forms.HiddenInput)

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CustomUserCreationForm, ComentarioForm  
from .models import Cursos, OtraClase, InscripcionCurso, Profesor, Comentario, Respuesta, Notificacion
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .forms import OtraClaseForm 
from django.http import HttpResponse
from channels.layers import get_channel_layer
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            fecha_nacimiento = request.POST.get('fecha_de_nacimiento')
            foto_perfil = request.FILES.get('foto_de_perfil')
            descripcion = request.POST.get('descripcion')
            OtraClase.objects.create(original=user, fecha_de_nacimiento=fecha_nacimiento, foto_de_perfil=foto_perfil, descripcion=descripcion)
            return redirect('user_logout')  
    else:
        form = CustomUserCreationForm()
    return render(request, 'signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('welcome')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('welcome')


def send_notification_to_channel(notification):
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        "notifications_channel_name",
        {
            "type": "send_notification",
            "notification": notification
        }
    )


def welcome(request):
    

    return render(request, 'welcome.html')

def lista_cursos(request):
    cursos = Cursos.objects.all()

    tipos = Cursos.objects.values_list('tipo', flat=True).distinct()

    años = Cursos.objects.values_list('años', flat=True).distinct()
    
    # Filtrar los cursos según lo solicitado
    tipo_filtrado = request.GET.get('tipo')
    años_filtrados = request.GET.get('años')
    if tipo_filtrado:
        cursos = cursos.filter(tipo=tipo_filtrado)
    if años_filtrados:
        cursos = cursos.filter(años=años_filtrados)
    
    return render(request, 'cursos.html', {'cursos': cursos, 'tipos': tipos, 'años': años})

@login_required(login_url='/login/')  # Este decorador asegura que el usuario esté autenticado
def detalle_curso(request, curso_id):
    curso = Cursos.objects.get(pk=curso_id)
    usuario_inscrito = InscripcionCurso.objects.filter(usuario=request.user, curso=curso).exists()
    return render(request, 'detalle_curso.html', {'curso': curso, 'usuario_inscrito': usuario_inscrito})


def inscribirse_curso(request, curso_id):
    if request.method == 'POST':
        curso = Cursos.objects.get(pk=curso_id)
        # Verificar si el usuario ya está inscrito en el curso
        if not InscripcionCurso.objects.filter(usuario=request.user, curso=curso).exists():
            # Crear una inscripción para el usuario en el curso
            InscripcionCurso.objects.create(usuario=request.user, curso=curso)
    
    # Redirigir a la página de detalles del curso recién inscrito
    return redirect('detalle_curso', curso_id=curso_id)


def perfil_usuario(request):
    usuario = request.user
    
    # Obtener el objeto OtraClase asociado al usuario, si existe
    try:
        otra_clase_info = OtraClase.objects.get(original=usuario)
    except OtraClase.DoesNotExist:
        otra_clase_info = None
    
    # Obtener la lista de cursos inscritos por el usuario
    cursos_inscritos = InscripcionCurso.objects.filter(usuario=usuario)
    
    # Obtener los comentarios del usuario
    comentarios_usuario = Comentario.objects.filter(alumno=usuario)
    
    return render(request, 'perfil.html', {'usuario': usuario, 'otra_clase_info': otra_clase_info, 'cursos_inscritos': cursos_inscritos, 'comentarios_usuario': comentarios_usuario})


def usuarios_inscritos_curso(request, curso_id):
    curso = get_object_or_404(Cursos, pk=curso_id)
    usuarios_inscritos = InscripcionCurso.objects.filter(curso=curso)
    return render(request, 'usuarios_inscritos_curso.html', {'curso': curso, 'usuarios_inscritos': usuarios_inscritos})


def lista_profe(request):
    # Obtener todos los profesores y todos los cursos
    profesores = Profesor.objects.all()
    cursos = Cursos.objects.all()

    # Obtener tipos únicos de cursos
    tipos_cursos = cursos.values_list('tipo', flat=True).distinct()

    # Obtener parámetros de filtrado
    nombre_filtrado = request.GET.get('nombre_curso')
    descripcion_filtrada = request.GET.get('descripcion_curso')
    tipo_filtrado = request.GET.get('tipo_curso')

    # Filtrar profesores según los parámetros de filtrado
    if nombre_filtrado:
        profesores = profesores.filter(cursos__nombre=nombre_filtrado)
    
    if descripcion_filtrada:
        profesores = profesores.filter(cursos__descripcion=descripcion_filtrada)
    
    if tipo_filtrado:
        profesores = profesores.filter(cursos__tipo=tipo_filtrado)

    return render(request, 'profes.html', {'profesores': profesores, 'tipos_cursos': tipos_cursos})




@login_required
def comentarios_alumno(request):
    comentarios = Comentario.objects.all()
    
    if request.method == 'POST':
        if 'texto' in request.POST:
            # Agregar un nuevo comentario
            texto = request.POST.get('texto')
            usuario = request.user
            alumno, creado = User.objects.get_or_create(username=usuario.username)
            Comentario.objects.create(alumno=alumno, texto=texto)
            return redirect('comentarios_alumno')
        elif 'like' in request.POST:
            # Dar o quitar like a un comentario
            comentario_id = request.POST.get('comentario_id')
            comentario = Comentario.objects.get(pk=comentario_id)
            comentario.toggle_like(request.user)
            comentario.save()
            return redirect('comentarios_alumno')

    return render(request, 'comentarios_alumno.html', {'comentarios': comentarios})
                
        

    
def nueva_respuesta(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    respuestas = Respuesta.objects.filter(comentario_padre=comentario)
    
    if request.method == 'POST':
        texto = request.POST.get('texto')
        autor = request.user
        respuesta = Respuesta.objects.create(comentario_padre=comentario, autor=autor, texto=texto)
        
        # Obtener el destinatario de la notificación (creador del comentario original)
        destinatario = comentario.alumno
        
        # Crear notificación de respuesta
        Notificacion.create_response_notification(comentario, autor, destinatario=destinatario)
        
        return redirect('nueva_respuesta', comentario_id=comentario_id)
    
    # Obtener las notificaciones no vistas del usuario actual
    notificaciones = Notificacion.objects.filter(destinatario=request.user, vista=False)
    # Marcar las notificaciones como vistas
    notificaciones.update(vista=True)
    
    return render(request, 'nueva_respuesta.html', {'comentario': comentario, 'respuestas': respuestas, 'notificaciones': notificaciones})


def editar_comentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    
    # Verificar si el usuario tiene permiso para editar el comentario
    if request.user == comentario.alumno:
        if request.method == 'POST':
            form = ComentarioForm(request.POST, instance=comentario)
            if form.is_valid():
                form.save()
                return redirect('perfil_usuario')
        else:
            form = ComentarioForm(instance=comentario)
        
        return render(request, 'editar_comentario.html', {'form': form, 'comentario': comentario})
    else:
        # Manejar caso donde el usuario no tiene permisos para editar el comentario
        return redirect('perfil_usuario')  # O mostrar algún mensaje de error


def eliminar_comentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, pk=comentario_id)
    
    # Verificar si el usuario tiene permiso para eliminar el comentario
    if request.user == comentario.alumno:
        comentario.delete()
    
    return redirect('perfil_usuario')







from asgiref.sync import async_to_sync

def mostrar_notificaciones(request):
    if request.user.is_authenticated:
        notificaciones = Notificacion.objects.filter(destinatario=request.user).order_by('-fecha_creacion')
        respuestas = Respuesta.objects.filter(autor=request.user)
        notificaciones_no_vistas = notificaciones.filter(vista=False)
        tiene_notificaciones_no_vistas = notificaciones_no_vistas.exists()

        if tiene_notificaciones_no_vistas:
            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                f"notifications_{request.user.id}",
                {
                    "type": "send_notification",
                    "notification": "Tienes nuevas notificaciones"
                }
            )

        notificaciones_no_vistas.update(vista=True)

        return render(request, 'notificaciones.html', {
            'notificaciones': notificaciones,
            'respuestas': respuestas,
            'notificaciones_no_vistas': tiene_notificaciones_no_vistas
        })
    
def editar_perfil_usuario(request):
    # Obtener el objeto OtraClase asociado al usuario actual, si existe
    try:
        otra_clase_info = OtraClase.objects.get(original=request.user)

myapp/templates/comentarios_alumno.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Comentario</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/comentarios.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/barra.css' %}">

    <script>
        function toggleLike(button) {
            if (button.innerHTML === 'Like') {
                button.innerHTML = 'Unlike';
            } else {
                button.innerHTML = 'Like';
            }
        }
    </script>
    <style>
        /* Agrega tus estilos aquí */
    </style>
</head>
<body>
    <ul class="navbar-links">
        <li><a href="/">home</a></li>
        {% if user.is_authenticated %}
        <li><a href="/comentarios_alumno/">Comentarios Alumno</a></li>
        {% endif %}    <li><a href="/profe/">Profesores</a></li>
        <li><a href="/lista-cursos/">Lista Cursos</a></li>
    
        {% if user.is_authenticated %}
        <li><a href="{% url 'cursos_inscritos' %}">Tus inscripciones</a></li>
        <li><a href="/perfil/">Perfil</a></li>
        <li>
            <a href="#" id="notificaciones" data-url="{% url 'notificaciones' %}" class="notificaciones-link {{ notificaciones_class }}">{{ notificaciones_no_vistas }} Notificaciones</a>
        </li>
        {% endif %}
    
        <li>
          {% if user.is_authenticated %}
          <a href="{% url 'user_logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'user_login' %}">Login</a>
          {% endif %}
        </li>
    </ul>
    <div class="container">
        <h1>Comentarios del Alumno</h1>
        <!-- Formulario para agregar un nuevo comentario -->
        <form method="post" action="{% url 'comentarios_alumno' %}">
            {% csrf_token %}
            <label for="texto">Contenido:</label><br>
            <textarea id="texto" name="texto"></textarea><br>
            <button type="submit">Agregar Comentario</button>
        </form>
        <h2>Comentarios</h2>
        <ul>
            <!-- Iterar sobre todos los comentarios -->
            {% for comentario in comentarios %}
            <li class="tweet-container">
                <div class="tweet-header">
                    <!-- Mostrar el nombre de usuario y la fecha de creación del comentario -->
                    <span class="tweet-username">{{ comentario.alumno.username }}</span>
                    <span class="tweet-timestamp">{{ comentario.fecha_creacion }}</span>
                </div>
                <!-- Mostrar el contenido del comentario -->
                <p class="tweet-text">{{ comentario.texto }}</p>
                <!-- Mostrar la cantidad de likes del comentario -->
                <p>Likes: {{ comentario.likes.count }}</p>
                <!-- Formulario para dar o quitar like al comentario -->
                <form method="post" action="{% url 'comentarios_alumno' %}">
                    {% csrf_token %}
                    <input type="hidden" name="comentario_id" value="{{ comentario.id }}">
                    <!-- El botón de "like" debe estar deshabilitado si el usuario no está autenticado -->
                    <button type="submit" name="like" {% if not user.is_authenticated %} disabled {% endif %}>Like</button>
                </form>
                <!-- Botón para responder al comentario -->
                <button onclick="location.href='{% url 'nueva_respuesta' comentario.id %}'">Responder</button>
                <!-- Botón para mostrar/ocultar las respuestas -->
                <button class="toggle-responses-btn">Mostrar Respuestas</button>
                
                <!-- Mostrar las respuestas al comentario -->
                <ul class="respuestas" style="display: none;">
                    {% for respuesta in comentario.respuestas.all %}
                    <li>{{ respuesta.autor.username }} - {{ respuesta.texto }}</li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    </div>

    <script>
        // JavaScript para mostrar/ocultar las respuestas al hacer clic en el botón
        const toggleResponsesBtns = document.querySelectorAll('.toggle-responses-btn');

        toggleResponsesBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                const responsesList = btn.nextElementSibling;
                if (responsesList.style.display === 'none') {
                    responsesList.style.display = 'block';
                    btn.textContent = 'Ocultar Respuestas';
                } else {
                    responsesList.style.display = 'none';
                    btn.textContent = 'Mostrar Respuestas';
                }
            });
        });
    </script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>

myapp/templates/cursos.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Cursos</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/items.css' %}">

    
</head>
<body>
    <ul class="navbar-links">
        <li><a href="/">home</a></li>
        {% if user.is_authenticated %}
        <li><a href="/comentarios_alumno/">Comentarios Alumno</a></li>
        {% endif %}    <li><a href="/profe/">Profesores</a></li>
        <li><a href="/lista-cursos/">Lista Cursos</a></li>
    
        {% if user.is_authenticated %}
        <li><a href="{% url 'cursos_inscritos' %}">Tus inscripciones</a></li>
        <li><a href="/perfil/">Perfil</a></li>
        <li>
            <a href="#" id="notificaciones" data-url="{% url 'notificaciones' %}" class="notificaciones-link {{ notificaciones_class }}">{{ notificaciones_no_vistas }} Notificaciones</a>
        </li>
        {% endif %}
    
        <li>
          {% if user.is_authenticated %}
          <a href="{% url 'user_logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'user_login' %}">Login</a>
          {% endif %}
        </li>
    </ul>
    <h1>Lista de Cursos</h1>
    
    <!-- Formulario de filtro -->
    <form method="GET">
        <label for="tipo">Tipo:</label>
        <select name="tipo" id="tipo">
            <option value="">Todos</option>
            {% for tipo in tipos %}
                <option value="{{ tipo }}" {% if tipo == tipo_filtrado %}selected{% endif %}>{{ tipo }}</option>
            {% endfor %}
        </select>
        
        <label for="años">Año:</label>
        <select name="años" id="años">
            <option value="">Todos</option>
            {% for año in años %}
                <option value="{{ año }}" {% if año == años_filtrados %}selected{% endif %}>{{ año }}</option>
            {% endfor %}
        </select>
        
        <button type="submit">Filtrar</button>
    </form>
    
    <!-- Lista de cursos -->
    <ul>
        {% for curso in cursos %}
            <li>
                <!-- Enlace al detalle del curso -->
                <span class="separador"></span> <!-- Línea vertical -->

                <a href="{% url 'detalle_curso' curso.id %}" class="curso-nombre">{{ curso.nombre }}</a>
                <hr>
                <span class="separador"></span> <!-- Línea vertical -->
                <hr>
            </li>
        
        {% endfor %}
    </ul>
</body>
</html>

myapp/templates/detalle_curso.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Detalles del Curso</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <ul class="navbar-links">
        <li><a href="/">home</a></li>
        {% if user.is_authenticated %}
        <li><a href="/comentarios_alumno/">Comentarios Alumno</a></li>
        {% endif %}    <li><a href="/profe/">Profesores</a></li>
        <li><a href="/lista-cursos/">Lista Cursos</a></li>
    
        {% if user.is_authenticated %}
        <li><a href="{% url 'cursos_inscritos' %}">Tus inscripciones</a></li>
        <li><a href="/perfil/">Perfil</a></li>
        <li>
            <a href="#" id="notificaciones" data-url="{% url 'notificaciones' %}" class="notificaciones-link {{ notificaciones_class }}">{{ notificaciones_no_vistas }} Notificaciones</a>
        </li>
        {% endif %}
    
        <li>
          {% if user.is_authenticated %}
          <a href="{% url 'user_logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'user_login' %}">Login</a>
          {% endif %}
        </li>
    </ul>
    <h1>{{ curso.nombre }}</h1>
    <p><strong></strong> {{ curso.decribcion }}</p>
    <p><strong></strong> {{ curso.tipo }}</p>
    <p><strong></strong> {{ curso.años }}</p>
    
    {% if usuario_inscrito %}
        <p>Ya estás inscrito en este curso.</p>
    {% else %}
        <!-- Botón para inscribirse en el curso -->
        <form action="{% url 'inscribirse_curso' curso.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Inscribirse en el curso</button>
        </form>
    {% endif %}
    <br>
    <!-- Botón para volver a la página de inicio -->
    <a href="{% url 'welcome' %}"><button>Volver a la bienvenida</button></a>
</body>
</html>

myapp/templates/editar_comentario.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Comentario</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <h1>Editar Comentario</h1>
    <p>Comentario actual: {{ comentario.texto }}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>
</body>
</html>

myapp/templates/editar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Perfil de Usuario</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
<h1>Editar Perfil</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
</form>

</body>
</html>

myapp/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <script>
        // Función para establecer la fecha actual en el campo de fecha de nacimiento
        function setTodayDate() {
            var today = new Date().toISOString().split('T')[0];
            document.getElementById('id_fecha_de_nacimiento').value = today;
        }
    </script>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        <!-- Campo de fecha de nacimiento con la fecha actual -->
        <label for="id_fecha_de_nacimiento">Fecha de Nacimiento:</label>
        <input type="date" id="id_fecha_de_nacimiento" name="fecha_de_nacimiento">
        
        <!-- Llamar a la función setTodayDate al cargar la página -->
        <script>setTodayDate();</script>
        
        <!-- Campo de foto de perfil -->
        <label for="id_foto_de_perfil">Foto de Perfil:</label>
        <input type="file" id="id_foto_de_perfil" name="foto_de_perfil">
        
        <!-- Campo de descripción -->
        <label for="id_descripcion">Descripción:</label>
        <textarea id="id_descripcion" name="descripcion"></textarea>
        
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>